package view;

/**
 * Đây là cửa sổ chính của ứng dụng.
 * NetBeans sẽ tự động tạo mã nguồn cho các thành phần giao diện.
 * Bạn chỉ cần thêm các sự kiện cho nút bấm.
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        // Căn giữa cửa sổ khi hiển thị
        setLocationRelativeTo(null); 
        setTitle("Phần Mềm Quản Lý Bán Hàng - Cửa Hàng Nem Chua");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        btnProductManagement = new javax.swing.JButton();
        btnSales = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnProductManagement.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnProductManagement.setText("Quản Lý Sản Phẩm");
        btnProductManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductManagementActionPerformed(evt);
            }
        });

        btnSales.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSales.setText("Bán Hàng");

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("TRANG CHỦ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSales, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProductManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(102, Short.MAX_VALUE))
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTitle)
                .addGap(42, 42, 42)
                .addComponent(btnProductManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnSales, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void btnProductManagementActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        // TODO: Mở cửa sổ ProductManagementView tại đây
        // ProductManagementView productView = new ProductManagementView();
        // productView.setVisible(true);
    }                                                    

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnProductManagement;
    private javax.swing.JButton btnSales;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration                   
}
