/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.ProductController;
import model.Product;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

/**
 *
 * @author ADMIN
 */
public class ProductManagementView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProductManagementView.class.getName());

    private ProductController productController;
   
    private DefaultTableModel tableModel;
    
    public ProductManagementView() {
        initComponents();
        this.productController = new ProductController();
        this.tableModel = (DefaultTableModel) productTable.getModel();
        Dimension fieldSize = new Dimension(180, 30); 
        txtId.setPreferredSize(fieldSize);
        txtName.setPreferredSize(fieldSize);
        txtUnit.setPreferredSize(fieldSize);
        txtPrice.setPreferredSize(fieldSize);
        txtQuantity.setPreferredSize(fieldSize);
        txtNote.setPreferredSize(fieldSize);
        updateButtonState(false);
        addTableListener();
        loadProductData();
    }
    private void loadProductData() {
        //Xoa du lieu cu 
        tableModel.setRowCount(0);

        //Lấy danh sách sản phẩm từ controller
        List<Product> products = productController.getAllProducts();
        
        //Thêm từng sản phẩm vào bang
        for (Product p : products) {
            tableModel.addRow(new Object[]{
                p.getId(),
                p.getName(),
                p.getUnit(),
                p.getPrice(),
                p.getQuantity(),
                p.getNote()
            });
        }
    }
    private void clearForm() {
        txtId.setText("");
        txtName.setText("");
        txtUnit.setText("");
        txtPrice.setText("");
        txtQuantity.setText("");
        txtNote.setText("");
        productTable.clearSelection(); 
        updateButtonState(false); //Cập nhật trạng thái nút 
    }
    
    private void updateButtonState(boolean rowIsSelected) {
        btnAdd.setEnabled(!rowIsSelected);
        btnUpdate.setEnabled(rowIsSelected); 
        btnDelete.setEnabled(rowIsSelected);
    }

    private void addTableListener() {
    productTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
        @Override
        public void valueChanged(ListSelectionEvent e) {
            if (!e.getValueIsAdjusting() && productTable.getSelectedRow() != -1) {
                int selectedRow = productTable.getSelectedRow();

                //Lấy dữ liệu 
                txtId.setText(tableModel.getValueAt(selectedRow, 0).toString());
                txtName.setText(tableModel.getValueAt(selectedRow, 1).toString());
                txtUnit.setText(tableModel.getValueAt(selectedRow, 2).toString());
                txtPrice.setText(tableModel.getValueAt(selectedRow, 3).toString());
                txtQuantity.setText(tableModel.getValueAt(selectedRow, 4).toString());

                Object noteObj = tableModel.getValueAt(selectedRow, 5);
                txtNote.setText(noteObj != null ? noteObj.toString() : "");

                updateButtonState(true);
            }
        }
    });
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        scrollPane = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        southPanel = new javax.swing.JPanel();
        formPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtUnit = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNote = new javax.swing.JTextField();
        buttonPanel = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.BorderLayout(10, 10));

        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tên Sản Phẩm", "Đơn vị", "Giá", "Số lượng", "Ghi chú"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        productTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrollPane.setViewportView(productTable);

        getContentPane().add(scrollPane, java.awt.BorderLayout.CENTER);

        southPanel.setLayout(new java.awt.BorderLayout());

        formPanel.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("ID:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formPanel.add(jLabel1, gridBagConstraints);

        txtId.setEditable(false);
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formPanel.add(txtId, gridBagConstraints);

        jLabel2.setText("Giá (*):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formPanel.add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formPanel.add(txtPrice, gridBagConstraints);

        jLabel3.setText("Tên SP (*):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formPanel.add(jLabel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formPanel.add(txtName, gridBagConstraints);

        jLabel4.setText("Số lượng:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formPanel.add(jLabel4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formPanel.add(txtQuantity, gridBagConstraints);

        jLabel5.setText("Đơn vị:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formPanel.add(jLabel5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formPanel.add(txtUnit, gridBagConstraints);

        jLabel6.setText("Ghi chú:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formPanel.add(jLabel6, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formPanel.add(txtNote, gridBagConstraints);

        southPanel.add(formPanel, java.awt.BorderLayout.PAGE_START);

        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        buttonPanel.add(btnAdd);

        btnUpdate.setText("Cập nhật");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        buttonPanel.add(btnUpdate);

        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        buttonPanel.add(btnDelete);

        btnClear.setText("Làm mới Form");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        buttonPanel.add(btnClear);

        southPanel.add(buttonPanel, java.awt.BorderLayout.SOUTH);

        getContentPane().add(southPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        try {
                    //Lấy dữ liệu từ form
                    String name = txtName.getText();
                    String unit = txtUnit.getText();
                    double price = Double.parseDouble(txtPrice.getText());
                    int quantity = Integer.parseInt(txtQuantity.getText());
                    String note = txtNote.getText();

                    int newId = productController.addProduct(name, unit, price, quantity, note);

                    //Xử lý kết quả
                    if (newId != -1) {
                        JOptionPane.showMessageDialog(ProductManagementView.this, 
                                "Thêm sản phẩm thành công!", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                        loadProductData(); 
                        clearForm();     
                    } else {
                        JOptionPane.showMessageDialog(ProductManagementView.this, 
                                "Thêm sản phẩm thất bại. (Tên và Giá là bắt buộc, Giá > 0, SL >= 0)", 
                                "Lỗi", JOptionPane.ERROR_MESSAGE);
                    }

                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(ProductManagementView.this, 
                            "Giá và Số lượng phải là số hợp lệ.", 
                            "Lỗi Định Dạng", JOptionPane.ERROR_MESSAGE);
                }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        try {
                    //Lấy dữ liệu từ form
                    int id = Integer.parseInt(txtId.getText()); 
                    String name = txtName.getText();
                    String unit = txtUnit.getText();
                    double price = Double.parseDouble(txtPrice.getText());
                    int quantity = Integer.parseInt(txtQuantity.getText());
                    String note = txtNote.getText();

                    boolean success = productController.updateProduct(id, name, unit, price, quantity, note);

                    //Xử lý kết quả
                    if (success) {
                        JOptionPane.showMessageDialog(ProductManagementView.this, 
                                "Cập nhật sản phẩm thành công!", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                        loadProductData(); 
                        clearForm();       
                    } else {
                        JOptionPane.showMessageDialog(ProductManagementView.this, 
                                "Cập nhật sản phẩm thất bại. (Tên và Giá là bắt buộc, Giá > 0)", 
                                "Lỗi", JOptionPane.ERROR_MESSAGE);
                    }

                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(ProductManagementView.this, 
                            "ID, Giá và Số lượng phải là số hợp lệ.", 
                            "Lỗi Định Dạng", JOptionPane.ERROR_MESSAGE);
                }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        try {
                    int id = Integer.parseInt(txtId.getText()); 

                    //Yêu cầu xác nhận trước khi xóa
                    int confirm = JOptionPane.showConfirmDialog(ProductManagementView.this,
                            "Bạn có chắc chắn muốn xóa sản phẩm này? (ID: " + id + ")",
                            "Xác Nhận Xóa",
                            JOptionPane.YES_NO_OPTION);

                    if (confirm == JOptionPane.YES_OPTION) {
                        boolean success = productController.deleteProduct(id);

                        //Xử lý kết quả
                        if (success) {
                            JOptionPane.showMessageDialog(ProductManagementView.this, 
                                    "Xóa sản phẩm thành công!", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                            loadProductData();
                            clearForm();
                        } else {
                            JOptionPane.showMessageDialog(ProductManagementView.this, 
                                    "Xóa sản phẩm thất bại. (Có thể sản phẩm đã tồn tại trong một đơn hàng).", 
                                    "Lỗi", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(ProductManagementView.this, 
                            "ID sản phẩm không hợp lệ.", 
                            "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
    }//GEN-LAST:event_btnDeleteActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ProductManagementView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel formPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTable productTable;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JPanel southPanel;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNote;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtUnit;
    // End of variables declaration//GEN-END:variables
}
