/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
// Dan cac dong nay vao ngay duoi "package view;"
import controller.ProfitController; // Import "bo nao"
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane; // De hien thi thong bao
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import model.Profit;
import java.text.NumberFormat; // De dinh dang tien te

/**
 *
 * @author duong
 */
public class ProfitView extends javax.swing.JFrame {
    // Khai bao "bo nao"
    private ProfitController profitController;
    private NumberFormat currencyFormatter; // Bien de dinh dang tien te
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProfitView.class.getName());

    /**
     * Creates new form ProfitView
     */
    public ProfitView() {
        initComponents();
        
        // Khoi tao "bo nao"
        this.profitController = new ProfitController();
        
        // Khoi tao bo dinh dang tien te
        this.currencyFormatter = NumberFormat.getCurrencyInstance(new java.util.Locale("vi", "VN"));
        
        // Thiet lap bang
        setupTable();
        
        // Tai du lieu lich su loi nhuan len bang
        loadProfitTable();
    }
    
    /**
     * Thiet lap (dinh nghia) cac cot cho bang profitTable
     */
    private void setupTable() {
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Khong cho phep sua truc tiep tren bang
            }
        };
        model.addColumn("ID");
        model.addColumn("Ngay");
        model.addColumn("Doanh Thu");
        model.addColumn("Chi Phi Thit");
        model.addColumn("Chi Phi Gia Vi");
        model.addColumn("Chi Phi La");
        model.addColumn("Chi Phi Nhan Cong");
        model.addColumn("LOI NHUAN RONG");
        profitTable.setModel(model);
        profitTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    
    /**
     * Tai danh sach ban ghi loi nhuan tu Controller va do vao bang
     */
    private void loadProfitTable() {
        DefaultTableModel model = (DefaultTableModel) profitTable.getModel();
        model.setRowCount(0); // Xoa het du lieu cu
        
        List<Profit> profits = profitController.getAllProfitRecords();
        for (Profit p : profits) {
            model.addRow(new Object[]{
                p.getId(),
                p.getDate(),
                currencyFormatter.format(p.getRevenue()), // Dinh dang tien te
                currencyFormatter.format(p.getCostMeat()),
                currencyFormatter.format(p.getCostSpices()),
                currencyFormatter.format(p.getCostLeaf()),
                currencyFormatter.format(p.getCostLabor()),
                currencyFormatter.format(p.getNetProfit()) // Dinh dang tien te
            });
        }
    }
    
    /**
     * Xoa trang cac o text field sau khi them
     */
    private void clearFields() {
        txtRevenue.setText("");
        txtCostMeat.setText("");
        txtCostSpices.setText("");
        txtCostLeaf.setText("");
        txtCostLabor.setText("");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtRevenue = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCostMeat = new javax.swing.JTextField();
        txtCostSpices = new javax.swing.JTextField();
        txtCostLeaf = new javax.swing.JTextField();
        txtCostLabor = new javax.swing.JTextField();
        btnAddProfit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        profitTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("BẢN GHI DOANH THU HÔM NAY"));

        jLabel1.setText("Doanh Thu:");

        txtRevenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRevenueActionPerformed(evt);
            }
        });

        jLabel2.setText("Chi Phí Thịt:");

        jLabel3.setText("Chi Phí Gia Vị:");

        jLabel4.setText("Chi Chí Lá");

        jLabel5.setText("Chi Phí Nhân Công");

        btnAddProfit.setText("SAVE");
        btnAddProfit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProfitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtRevenue)
                    .addComponent(txtCostMeat)
                    .addComponent(txtCostSpices)
                    .addComponent(txtCostLeaf)
                    .addComponent(txtCostLabor, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddProfit)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCostMeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtCostSpices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCostLeaf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCostLabor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddProfit)
                .addContainerGap())
        );

        profitTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(profitTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRevenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRevenueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRevenueActionPerformed

    private void btnAddProfitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProfitActionPerformed
        // TODO add your handling code here:
        // (Code khong dau de tranh loi font)
        try {
            // 1. Lay du lieu tu cac o text field
            // (Chuyen doi chuoi rong thanh "0" de tranh loi NumberFormatException)
            double revenue = Double.parseDouble(txtRevenue.getText().isEmpty() ? "0" : txtRevenue.getText());
            double costMeat = Double.parseDouble(txtCostMeat.getText().isEmpty() ? "0" : txtCostMeat.getText());
            double costSpices = Double.parseDouble(txtCostSpices.getText().isEmpty() ? "0" : txtCostSpices.getText());
            double costLeaf = Double.parseDouble(txtCostLeaf.getText().isEmpty() ? "0" : txtCostLeaf.getText());
            double costLabor = Double.parseDouble(txtCostLabor.getText().isEmpty() ? "0" : txtCostLabor.getText());

            // Lay ngay hom nay
            Date today = new Date();

            // 2. Goi "bo nao" (Controller) de xu ly
            boolean success = profitController.addProfitRecord(today, revenue, costMeat, costSpices, costLeaf, costLabor);

            // 3. Xu ly ket qua
            if (success) {
                JOptionPane.showMessageDialog(this, "Them ban ghi loi nhuan thanh cong!", "Thanh Cong", JOptionPane.INFORMATION_MESSAGE);
                loadProfitTable(); // Tai lai bang
                clearFields(); // Xoa trang form
            } else {
                JOptionPane.showMessageDialog(this, "Them that bai! (Kiem tra cac so lieu khong duoc am)", "Loi", JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Vui long nhap dung dinh dang so (Number) cho cac o!", "Loi Dinh Dang", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Da xay ra loi: " + e.getMessage(), "Loi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddProfitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ProfitView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProfit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable profitTable;
    private javax.swing.JTextField txtCostLabor;
    private javax.swing.JTextField txtCostLeaf;
    private javax.swing.JTextField txtCostMeat;
    private javax.swing.JTextField txtCostSpices;
    private javax.swing.JTextField txtRevenue;
    // End of variables declaration//GEN-END:variables
}
